name: sdfmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.11
  - scipy>=1.3
  - tqdm
  - joblib>=0.14.1
  - pandas>=1.0
  - matplotlib
  - scikit-learn>=0.24
  - xgboost
  - jupyter>=1.0
  - xlrd
